#!/usr/bin/env bash
# Pull Firebase web config from Google Secret Manager into apps/web/.env.local
# (secondSet-style: secret names match env vars; never commit .env.local).
#
# Prereqs:
#   gcloud auth login
#   gcloud config set project recess-app-nyc
#
# Usage:
#   bash scripts/pull-secrets.sh
#
# Rotate the browser API key:
#   1) Create a new restricted browser key in GCP API Keys
#   2) Update Secret Manager (NEXT_PUBLIC_FIREBASE_API_KEY + FIREBASE_WEB_CONFIG)
#   3) bash scripts/pull-secrets.sh && npm run build && npm run deploy:hosting
#   4) Delete the old API key in GCP
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT="${GOOGLE_CLOUD_PROJECT:-recess-app-nyc}"
OUT="${ROOT}/apps/web/.env.local"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "Fetching FIREBASE_WEB_CONFIG from Secret Manager (project=${PROJECT})…"
gcloud secrets versions access latest \
  --secret=FIREBASE_WEB_CONFIG \
  --project="${PROJECT}" >"$TMP"

python3 - "$OUT" "$TMP" <<'PY'
import json
import sys

out_path = sys.argv[1]
cfg_path = sys.argv[2]
with open(cfg_path, encoding="utf-8") as f:
    cfg = json.load(f)

required = [
    "NEXT_PUBLIC_FIREBASE_API_KEY",
    "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
    "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
    "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
    "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
    "NEXT_PUBLIC_FIREBASE_APP_ID",
]
missing = [k for k in required if not cfg.get(k)]
if missing:
    raise SystemExit(f"FIREBASE_WEB_CONFIG missing keys: {', '.join(missing)}")

lines = [
    "# Generated by scripts/pull-secrets.sh — do not commit",
    f"NEXT_PUBLIC_FIREBASE_API_KEY={cfg['NEXT_PUBLIC_FIREBASE_API_KEY']}",
    f"NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN={cfg['NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN']}",
    f"NEXT_PUBLIC_FIREBASE_PROJECT_ID={cfg['NEXT_PUBLIC_FIREBASE_PROJECT_ID']}",
    f"NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET={cfg['NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET']}",
    f"NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID={cfg['NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID']}",
    f"NEXT_PUBLIC_FIREBASE_APP_ID={cfg['NEXT_PUBLIC_FIREBASE_APP_ID']}",
    f"NEXT_PUBLIC_FIREBASE_FUNCTIONS_REGION={cfg.get('NEXT_PUBLIC_FIREBASE_FUNCTIONS_REGION', 'us-central1')}",
    "",
]
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"Wrote {out_path}")
PY
